name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * 0'

jobs:

  build_sdist_and_wheel:
    name: Build sdist and wheel
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install build requirements
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake
          pip install --upgrade -r build_requirements.txt

      - name: make
        shell: bash
        run: |
          python -m build

      - name: upload sdist and wheel
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      - name: Install wheel
        run: |
          pip install dist/*.whl

      - name: Install test requirements & set configuration variables
        run: |
          pip install -r test_requirements.txt

      - name: test
        shell: bash
        run: |
          python -m pytest -rsap -x -m "not requires_ase" tests

      - name: make with ase
        shell: bash
        run: |
          pip install ".[ase]"

      - name: test with requires_ase
        shell: bash
        run: |
          python -m pytest -rsap -x -m "requires_ase" tests

      - name: Install doc requirements
        run: |
          pip install -r doc_requirements.txt

      - name: build docs
        shell: bash
        run: |
          cd doc
          sphinx-build -b html . _build/html

      - name: upload docs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: casm-tools-docs
          path: doc/_build/html
