name: Testing Python versions on ubuntu-latest

on:
  schedule:
    - cron: '0 12 * * 0'
  workflow_dispatch: # Allows manual triggering

env:
  SKBUILD_BUILD_OPTIONS: --verbose

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build requirements
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake
          pip install --upgrade -r build_requirements.txt

      - name: make
        shell: bash
        run: |
          pip install .

      - name: Install test requirements & set configuration variables
        run: |
          pip install -r test_requirements.txt

      - name: test
        shell: bash
        run: |
          python -m pytest -rsap -x -m "not requires_ase" tests

      - name: make with ase
        shell: bash
        run: |
          pip install ".[ase]"

      - name: test with requires_ase
        shell: bash
        run: |
          python -m pytest -rsap -x -m "requires_ase" tests
